$ProjectRef = "xebhujvszurydytlrhra"

Write-Host "1) Faça login no Supabase com uma conta que tenha acesso ao projeto:"
Write-Host "npx supabase login"
Write-Host ""
Write-Host "2) Depois rode o deploy da Edge Function:"
Write-Host "npx supabase functions deploy verify-google-play-purchase --project-ref $ProjectRef"
Write-Host ""
Write-Host "3) Configure os secrets da Google Play API:"
Write-Host "npx supabase secrets set GOOGLE_PLAY_PACKAGE_NAME=`"com.becoslab.elite2050`" --project-ref $ProjectRef"
Write-Host "npx supabase secrets set GOOGLE_PLAY_SERVICE_ACCOUNT_JSON=`"{cole_aqui_o_json_da_service_account}`" --project-ref $ProjectRef"
Write-Host ""
Write-Host "4) Confira se a função subiu:"
Write-Host "npx supabase functions list --project-ref $ProjectRef"
