import React from 'react';
import { useGame } from '../store/GameContext';
import { calculateTeamPower, getTeamPowerCap } from '../engine/gameLogic';
import { LeagueState, MatchResult, MatchStatus, TeamLogoMetadata } from '../types';
import {
    SEASON_DAYS
} from '../constants/gameConstants';

/**
 * Shape das partidas expostas para as telas do dashboard.
 * Difere de `Match` de propósito: já traz nome e escudo dos times resolvidos.
 * Todo campo de `Match` que a UI consome precisa estar aqui — omitir um campo
 * faz a feature correspondente morrer em silêncio (foi o que aconteceu com `revealed`).
 */
export interface MatchViewModel {
    id: string;
    round: number;
    date: string;
    time: string;
    home: string;
    away: string;
    homeId: string;
    awayId: string;
    homeTeamId: string;
    awayTeamId: string;
    homeLogo?: TeamLogoMetadata;
    awayLogo?: TeamLogoMetadata;
    homeScore?: number;
    awayScore?: number;
    played?: boolean;
    status?: MatchStatus;
    revealed?: boolean;
    result?: MatchResult | null;
    type: string;
}

export const useDashboardData = () => {
    const { state } = useGame();

    const userManager = state.userManagerId ? state.managers[state.userManagerId] : null;
    let userTeam = userManager?.career.currentTeamId ? state.teams[userManager.career.currentTeamId] : null;

    if (!userTeam && state.userTeamId) {
        userTeam = state.teams[state.userTeamId] || null;
    }

    const baseDate = new Date(state.world.currentDate || new Date().toISOString());
    const seasonStartReal = state.world.seasonStartReal ? new Date(state.world.seasonStartReal) : null;

    // gameDate is now exactly baseDate (1:1 Sync)
    const gameDate = baseDate;

    const totalPoints = userTeam ? calculateTeamPower(userTeam, state.players) : 0;

    const powerCap = React.useMemo(() => {
        return getTeamPowerCap(userTeam, state.players);
    }, [state.players, userTeam]);

    const pointsLeft = powerCap - totalPoints;

    const seasonDaysTotal = SEASON_DAYS;
    const msPerDay = 1000 * 60 * 60 * 24;

    let daysPassed = state.world.currentDay || 0;
    let seasonProgress = Math.min(100, Math.round((daysPassed / seasonDaysTotal) * 100));

    if (daysPassed === 0 && seasonStartReal) {
        const diffMs = baseDate.getTime() - seasonStartReal.getTime();
        if (diffMs > 0) {
            daysPassed = Math.floor(diffMs / msPerDay) + 1;
            seasonProgress = Math.min(100, Math.round((daysPassed / seasonDaysTotal) * 100));
        }
    }

    const userTeamMatches = React.useMemo(() => {
        if (!userTeam || !state.world?.leagues) return [];

        const leagues = Object.values(state.world.leagues) as LeagueState[];
        const userLeague = leagues.find(l => l.standings.some(s => s.teamId === userTeam.id));

        if (!userLeague || !userLeague.matches) return [];

        const currentRound = state.world.currentRound;
        const matches = userLeague.matches
            .filter(m => (m.homeTeamId === userTeam.id || m.awayTeamId === userTeam.id))
            .sort((a, b) => a.round - b.round);

        return matches.map(m => {
            const homeTeam = state.teams[m.homeTeamId];
            const awayTeam = state.teams[m.awayTeamId];

            // Use the date and time already stored on the match object
            // (generated by CalendarGenerator relative to seasonStartReal)
            const matchDate = m.date.split('T')[0];
            const matchTime = m.time || '16:00';

            return {
                id: m.id,
                round: m.round,
                date: matchDate,
                time: matchTime,
                home: homeTeam?.name || 'Unknown',
                away: awayTeam?.name || 'Unknown',
                // homeId/awayId sao os nomes historicos usados pelas telas;
                // homeTeamId/awayTeamId mantem compatibilidade com o tipo `Match`.
                homeId: m.homeTeamId,
                awayId: m.awayTeamId,
                homeTeamId: m.homeTeamId,
                awayTeamId: m.awayTeamId,
                homeLogo: homeTeam?.logo,
                awayLogo: awayTeam?.logo,
                homeScore: m.homeScore,
                awayScore: m.awayScore,
                played: m.played,
                status: m.status,
                // Sem este campo o relatorio cego morre: a Home revela o placar
                // na hora e o CTA "Revelar relatorio" nunca aparece.
                revealed: m.revealed,
                result: m.result,
                type: 'League'
            } satisfies MatchViewModel;
        });
    }, [userTeam, state.world.leagues, state.world.currentRound, state.teams, state.world.currentDate]);

    const upcomingMatches = React.useMemo(() => {
        return userTeamMatches.filter(m => !m.played);
    }, [userTeamMatches]);

    const pastMatches = React.useMemo(() => {
        return userTeamMatches.filter(m => m.played);
    }, [userTeamMatches]);

    const leaguesData = React.useMemo(() => {
        if (!state.world?.leagues) return {};

        const processLeague = (league: LeagueState) => {
            const sortedStandings = [...league.standings].sort((a, b) => {
                const pointsA = Number.isFinite(a.points) ? a.points : 0;
                const pointsB = Number.isFinite(b.points) ? b.points : 0;
                if (pointsB !== pointsA) return pointsB - pointsA;
                const gdA = (Number.isFinite(a.goalsFor) ? a.goalsFor : 0) - (Number.isFinite(a.goalsAgainst) ? a.goalsAgainst : 0);
                const gdB = (Number.isFinite(b.goalsFor) ? b.goalsFor : 0) - (Number.isFinite(b.goalsAgainst) ? b.goalsAgainst : 0);
                return gdB - gdA;
            });

            const formattedStandings = sortedStandings.map((stats, index) => {
                const goalsFor = Number.isFinite(stats.goalsFor) ? stats.goalsFor : 0;
                const goalsAgainst = Number.isFinite(stats.goalsAgainst) ? stats.goalsAgainst : 0;
                return {
                    position: index + 1,
                    teamId: stats.teamId,
                    team: state.teams[stats.teamId]?.name || 'Unknown',
                    logo: state.teams[stats.teamId]?.logo,
                    played: Number.isFinite(stats.played) ? stats.played : 0,
                    points: Number.isFinite(stats.points) ? stats.points : 0,
                    goalsFor,
                    goalsAgainst,
                    gd: goalsFor - goalsAgainst,
                    id: stats.teamId
                };
            });

            const leaguePlayers: { playerId: string; name: string; team: string; teamId: string; goals: number; rank: number }[] = [];
            league.standings.forEach(teamStats => {
                const team = state.teams[teamStats.teamId];
                if (team && team.squad) {
                    team.squad.forEach(playerId => {
                        const player = state.players[playerId];
                        if (player && player.history?.goals > 0) {
                            leaguePlayers.push({
                                playerId: player.id,
                                name: player.name,
                                team: team.name,
                                teamId: team.id,
                                goals: player.history.goals,
                                rank: 0
                            });
                        }
                    });
                }
            });

            const sortedScorers = leaguePlayers
                .sort((a, b) => b.goals - a.goals)
                .slice(0, 10)
                .map((p, i) => ({ ...p, rank: i + 1 }));

            return {
                name: league.name,
                standings: formattedStandings,
                scorers: sortedScorers
            };
        };

        const processedLeagues: Record<string, any> = {};
        Object.keys(state.world.leagues).forEach(key => {
            if (state.world.leagues[key]) {
                processedLeagues[key] = processLeague(state.world.leagues[key] as LeagueState);
            }
        });
        return processedLeagues;
    }, [state.world, state.teams, state.players]);

    return {
        userManager,
        userTeam,
        baseDate,
        gameDate,
        totalPoints,
        powerCap,
        pointsLeft,
        seasonProgress,
        daysPassed,
        userTeamMatches,
        upcomingMatches,
        pastMatches,
        leaguesData
    };
};
